FROM archlinux

LABEL version="0.1.0"
LABEL maintainer="haru"
LABEL name="1-4-kosensai-archive"

RUN pacman -Syu --noconfirm 
RUN pacman -S --noconfirm nodejs
RUN pacman -S --noconfirm npm
RUN pacman -S --noconfirm yarn
RUN pacman -S --noconfirm git
RUN pacman -S --noconfirm github-cli

ENV PATH /root/.local/bin:$PATH